### ISSUE TITLE
Feature Request: Generate resolution-aware variants

### ISSUE THREAD

**Issue by wiesnery** [leancodepl/flutter_webp#14]
I am thinking whether it could be useful to generate resolution-aware variants of the webp output automatically.

Lets say I input an image with 10.000px x 10.000px and I set a target size of 1000 x 1000 so that it generates

- image.webp (1000px x 1000px)
- /2.0x/image.webp (2000px x 2000px)
- /3.0x/image.webp (3000px x 3000px)

Is this anyhow doable with the provided API and is this any useful with the webp format?
I am not aware of the details of the webp format and whether this could improve performance (I am assuming no cause the p stands for progressive loading, right?) and size (maybe not as the resolution specific variants are all bundled anyways as long as they are not stored in the native android/iOS asset folders I think).

Happy to get feedback on this and to provide implementation help once we figured out if this is useful and doable.

Cheers!

**Comment by Albert221** [comment]
Hey!

> Is this anyhow doable with the provided API?

The asset transformers API currently allows only the transformation of one asset into one asset, we cannot create _n_ assets based on one like you proposed. If you think that's a good case (maybe not for the `webp` package specifically) you should definitely create an issue on https://github.com/flutter/flutter.

> whether this could improve performance

I am not well familiar with the technicalities of the WebP format and its implementation in Flutter either, but it would make the transformation itself during compile/build time longer, as the CI/developer's machine would need to scale such images down. As for the performance on end-user devices, yes, serving assets more appropriate images based on the pixel density of the user's device will make it so that the device won't need to make such heavy scaling locally, but will already be supplied with an asset in exactly (or close) resolution it expects.

> and size (maybe not as the resolution specific variants are all bundled anyways as long as they are not stored in the native android/iOS asset folders I think)

What you answered yourself is right. Having resolution (or rather pixel-density) aware assets increase the size of the output app, it doesn't take advantage like Android App Bundles with native assets or the iOS counterpart would have - see https://github.com/flutter/flutter/issues/16015

As this is not doable with the current API and I believe is not the scope of this package, I'm closing the issue.

**Comment by wiesnery** [comment]
Hi @Albert221 

Thanks for the quick response to my inquiry!
Your answers came close to what I'd thought...
Please allow me one last question as it was a tedious search to find your package already.
I wasn't specifically looking for a webp asset converter but just wanted to shrink my image assets in size in general. Are you aware of another package which is not specific to webp?

Thank you in advance!
